#!/bin/bash
echo "\c postgres
CREATE DATABASE dfinder;
CREATE USER dfinder WITH PASSWORD '1q2w3e4r5T#' SUPERUSER;
ALTER ROLE dfinder WITH CREATEROLE CREATEDB REPLICATION BYPASSRLS;
CREATE USER pgpool WITH PASSWORD '1q2w3e4r5T#';
ALTER USER pgpool WITH LOGIN;
ALTER USER pgpool WITH REPLICATION;
GRANT ALL PRIVILEGES ON DATABASE dfinder TO dfinder;
GRANT CONNECT ON DATABASE dfinder TO pgpool;
GRANT USAGE ON SCHEMA public TO pgpool;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO pgpool;
ALTER DATABASE dfinder SET TIMEZONE='Asia/Seoul';
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO pgpool;" \
| psql -U postgres -p 15432 -d $1
